language: node_js
node_js:
  - 'stable'
install: npm install
services:
  - postgresql
addons:
  postgresql: '9.6'

cache:
  directories:
    - 'node_modules'
env:
  global:
    - DB_ENV=ci
before_script:
  - psql -c 'create database ldoor_test;' -U postgres
  - psql -c "CREATE USER randomuser WITH PASSWORD null;" -U postgres
  - npm install coveralls
  - npm i -g knex
  - knex migrate:latest --env=ci
script:
  - npm run ci:test
after_script:
  - jest --forceExit --coverage  --coverageReporters=text-lcov | coveralls
notifications:
  email: false
